StorForStudentsWebApp/StorForStudentsWebApp/Models/AdminCatalogViewModel.cs
using System.Collections;
using System.Collections.Generic;
using DomainLogic.Entities;

namespace StorForStudentsWebApp.Models
{
    public class AdminCatalogViewModel
    {
        public IList<ItemModel> itemList { get; protected set; }

        public AdminCatalogViewModel(IList<Item> list)
        {
            itemList = ItemModel.ToModel(list);
        }

        public AdminCatalogViewModel(IList<ItemModel> list)
        {
            itemList = list;
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Controllers/AddItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Implementation.Repositories;
using DomainLogic.Entities;
using DomainLogic.Repositories;
using DomainLogic.Utilities;
using StorForStudentsWebApp.Models;

namespace StorForStudentsWebApp.Controllers
{
    public class AddItemController : Controller
    {
        // GET: /AddItem/
        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /AddItem/Create
        [HttpPost]
        public ActionResult Create(ItemModel initem)
        {
            Asserts.IsNotNull(initem);
            Item outitem;
            // TODO: Add insert logic here
            using (var context = new StoreDbContext())
            {
                ItemsRepository repository = new ItemsRepository(context);
                outitem = initem.ConvertToItem();
                repository.SaveItem(outitem);
            }
            return RedirectToAction("Index", "AdminCatalog");
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Controllers/AdminCatalogController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DomainLogic.Entities;
using Implementation.Repositories;
using StorForStudentsWebApp.Models;
using DomainLogic.Repositories;
using System.Net;

namespace StorForStudentsWebApp.Controllers
{
    public class AdminCatalogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private int itemsOnPage = 15;

        // GET: AdminCatalog
        public ActionResult Index(int? page)
        {
            ViewBag.Pager = Pager.Items(100).PerPage(10).Move(page ?? 1).Segment(5).Center();
            if (page == null)
                page = 1;
            IList<ItemModel> itemList;
            using (var context = new StoreDbContext())
            {
                ItemsRepository repository = new ItemsRepository(context);
                itemList = ItemModel.ToModel(repository.GetAll());
            }
            List<ItemModel> resultList = new List<ItemModel>();
            long i=0;
            foreach (ItemModel itemModel in itemList)
            {
                if (i >= (page - 1) * itemsOnPage && i < (page) * itemsOnPage)
                    resultList.Add(itemModel);
                i++;
            }
            return View("Index", new AdminCatalogViewModel(resultList));
            //return View("Index", new AdminCatalogViewModel(itemList));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            using (StoreDbContext context = new StoreDbContext())
            {
                IItemsRepository repository = new ItemsRepository(context);
                Item item = repository.GetById(id);
                if (item == null)
                {
                    return RedirectToAction("Index");
                }
                ItemModel itemDTO = new ItemModel(item);
                return View(itemDTO);
            }
        }

        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (StoreDbContext context = new StoreDbContext())
            {
                IItemsRepository repository = new ItemsRepository(context);
                Item item = repository.GetById(id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ItemModel itemDBO = new ItemModel(item);
                return View(itemDBO);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemModel itemDBO)
        {
            if (ModelState.IsValid)
            {
                using (StoreDbContext context = new StoreDbContext())
                {
                    IItemsRepository repository = new ItemsRepository(context);
                    Item item = new Item();
                    item = itemDBO.ConvertToItem();
                    repository.AddItem(item);
                    return RedirectToAction("Index");
                }
            }
            return View(itemDBO);
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Controllers/DeleteItemController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DomainLogic.Entities;
using Implementation.Repositories;
using StorForStudentsWebApp.Models;
using DomainLogic.Utilities;

namespace StorForStudentsWebApp.Controllers
{
    public class DeleteItemController : Controller
    {
        //
        // GET: /DeleteItem/
        public ActionResult Index(ItemModel inItem)
        {
            Asserts.IsNotNull(inItem);
            // TODO: Add insert logic here
            using (var context = new StoreDbContext())
            {
                ItemsRepository repository = new ItemsRepository(context);
                Item delItem;
                delItem = repository.GetById(inItem.Id);
                repository.DeleteItem(delItem);
            }
            return RedirectToAction("Index", "AdminCatalog");
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Views/AdminCatalog/AdminCatalogTablePartialView.cshtml
@using StorForStudentsWebApp.Models
<table class="table table-striped table-hover">
    <tr>
        <th>
            Название товара
        </th>
        <th>
            Цена
        </th>
        <th>
            Количество
        </th>
        <th colspan="2">
            Удаление/Сведения
        </th>
    </tr>

    @foreach (ItemModel item in Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Price
            </td>
            <td>
                @item.Quantity
            </td>
            <td>
                @using (Html.BeginForm("Index", "DeleteItem",item))
                {
                    <div class="form-horizontal">
                        <input type="submit" value="Удалить" />
                    </div>
                }
            </td>
            <td>
                @using (Html.BeginForm("Details", "AdminCatalog", new { id = item.Id }))
                {
                    <div class="form-horizontal">
                        <input type="submit" value="Детали" />
                    </div>
                }
            </td>
        </tr>
    }
</table>

StorForStudentsWebApp/StorForStudentsWebApp/Views/AdminCatalog/Details.cshtml
@model StorForStudentsWebApp.Models.ItemModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ItemModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться назад", "Index")
</p>

StorForStudentsWebApp/StorForStudentsWebApp/Views/AdminCatalog/Edit.cshtml
@model StorForStudentsWebApp.Models.ItemModel

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Товар</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath)
                @Html.ValidationMessageFor(model => model.ImagePath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StorForStudentsWebApp/StorForStudentsWebApp/Views/AdminCatalog/Index.cshtml
@using StorForStudentsWebApp.Models
@model AdminCatalogViewModel

@{
    ViewBag.Title = "Редактор товаров.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Панель администратора. Редактор товаров.</h2>
@Html.Partial("AdminCatalogTablePartialView", Model.itemList)
@Html.Partial("PagePartialView")

<div>
    @Html.ActionLink("Добавить элемент", "Index", "AddItem")
</div>

StorForStudentsWebApp/StorForStudentsWebApp/Views/AdminCatalog/PagePartialView.cshtml
@using StorForStudentsWebApp.Controllers
@{
    Pager pager = ViewBag.Pager;

    if (pager.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = pager.FirstPageIndex });
    @Html.ActionLink("<", "Index", new { page = pager.PreviousPageIndex });
    }

    foreach (int page in ViewBag.Pager)
    {
        @Html.ActionLink(page.ToString(), "Index", new { page = page });
    }

    if (pager.HasNextPage)
    {
        @Html.ActionLink(">", "Index", new { page = pager.NextPageIndex });
    @Html.ActionLink(">>", "Index", new { page = pager.LastPageIndex });
    }
}