StorForStudentsWebApp/StorForStudentsWebApp/Controllers/AdminCatalogController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DomainLogic.Entities;
using Implementation.Repositories;
using StorForStudentsWebApp.Models;
using DomainLogic.Repositories;
using System.Net;

namespace StorForStudentsWebApp.Controllers
{
    public class AdminCatalogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private int itemsOnPage = 15;

        // GET: AdminCatalog
        public ActionResult Index(int? page)
        {
            ViewBag.Pager = Pager.Items(100).PerPage(10).Move(page ?? 1).Segment(5).Center();
            if (page == null)
                page = 1;
            IList<ItemModel> itemList;
            using (var context = new StoreDbContext())
            {
                ItemsRepository repository = new ItemsRepository(context);
                itemList = ItemModel.ToModel(repository.GetAll());
            }
            List<ItemModel> resultList = new List<ItemModel>();
            long i=0;
            foreach (ItemModel itemModel in itemList)
            {
                if (i >= (page - 1) * itemsOnPage && i < (page) * itemsOnPage)
                    resultList.Add(itemModel);
                i++;
            }
            return View("Index", new AdminCatalogViewModel(resultList));
            //return View("Index", new AdminCatalogViewModel(itemList));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            using (StoreDbContext context = new StoreDbContext())
            {
                IItemsRepository repository = new ItemsRepository(context);
                Item item = repository.GetById(id);
                if (item == null)
                {
                    return RedirectToAction("Index");
                }
                ItemModel itemDTO = new ItemModel(item);
                return View(itemDTO);
            }
        }

        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (StoreDbContext context = new StoreDbContext())
            {
                IItemsRepository repository = new ItemsRepository(context);
                Item item = repository.GetById(id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ItemModel itemDBO = new ItemModel(item);
                return View(itemDBO);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemModel itemDBO)
        {
            if (ModelState.IsValid)
            {
                using (StoreDbContext context = new StoreDbContext())
                {
                    IItemsRepository repository = new ItemsRepository(context);
                    Item item = new Item();
                    item = itemDBO.ConvertToItem();
                    repository.AddItem(item);
                    return RedirectToAction("Index");
                }
            }
            return View(itemDBO);
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Controllers/BucketPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StorForStudentsWebApp.Controllers
{
    public class BucketPartialController : Controller
    {
        public int GetItemsCountInOrder()
        {
            int itemsCount = 0;
            //TODO: подсчет количества предметов
            return itemsCount;
        }

        public decimal GetOrderPrice()
        {
            decimal orderPrice = 0;
            //TODO: подсчет общей цены
            return orderPrice;
        }
    }
}

StorForStudentsWebApp/StorForStudentsWebApp/Views/Shared/_BucketPartial.cshtml
@if (Request.IsAuthenticated)
{
    <div class="bucket-info navbar-right">
        В вашей корзине @Html.Action("GetItemsCountInOrder", "BucketPartial") предметов. <br/>
        Общая стоимость: @Html.Action("GetOrderPrice", "BucketPartial")р.
    </div>
}

StorForStudentsWebApp/StorForStudentsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Магазин студентов.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Магазин студентов", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("О магазине", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Панель администратора", "Index", "AdminCatalog")</li>
                </ul>
                @Html.Partial("_BucketPartial")
                @Html.Partial("_LoginPartial")
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Практика 2015.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>